import { AudioFile } from "../AudioFileType";


export const KanyeWestAudioFiles: AudioFile[] = [
    {
        id: 17,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/01%20Good%20Morning.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good Morning',
        duration: "03:15",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 18,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/02%20Champion.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Champion',
        duration: "02:48",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 19,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/03%20Stronger.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Stronger',
        duration: "05:12",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 20,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/04%20I%20Wonder.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Wonder',
        duration: "04:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 21,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/05%20Good%20Life%20(Feat.%20T-Pain).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good Life (Feat. T-Pain)',
        duration: "03:27",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 22,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/06%20Can't%20Tell%20Me%20Nothing.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: "Can't Tell Me Nothing",
        duration: "04:32",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 23,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/07%20Barry%20Bonds%20(Feat.%20Lil%20Wayne).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Barry Bonds (Feat. Lil Wayne)',
        duration: "03:24",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 24,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/08%20Drunk%20And%20Hot%20Girls%20(Feat.%20Mos%20Def).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Drunk And Hot Girls (Feat. Mos Def)',
        duration: "05:13",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 25,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/09%20Flashing%20Lights%20(Feat.%20Dwele).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Flashing Lights',
        duration: "03:58",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 26,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/10%20Everything%20I%20Am%20(Feat.%20DJ%20Premier).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Everything I Am (Feat. DJ Premier)',
        duration: "03:48",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 27,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/11%20The%20Glory.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'The Glory',
        duration: "03:33",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 28,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/12%20Homecoming%20(Feat.%20Chris%20Martin).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Homecoming',
        duration: "03:24",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 29,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/13%20Big%20Brother.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Big Brother',
        duration: "04:47",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 30,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/14%20Good%20Night.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good night',
        duration: "03:06",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 48,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/14%20Good%20Night.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good night',
        duration: "03:06",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
]