import { AudioFile } from "../AudioFileType";


export const KanyeWestAudioFiles: AudioFile[] = [
    {
        id: 17,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/01%20Good%20Morning.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good Morning',
        duration: "03:15",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 18,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/02%20Champion.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Champion',
        duration: "02:48",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 19,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/03%20Stronger.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Stronger',
        duration: "05:12",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 20,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/04%20I%20Wonder.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Wonder',
        duration: "04:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 21,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/05%20Good%20Life%20(Feat.%20T-Pain).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good Life (Feat. T-Pain)',
        duration: "03:27",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 22,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/06%20Can't%20Tell%20Me%20Nothing.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: "Can't Tell Me Nothing",
        duration: "04:32",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 23,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/07%20Barry%20Bonds%20(Feat.%20Lil%20Wayne).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Barry Bonds (Feat. Lil Wayne)',
        duration: "03:24",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 24,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/08%20Drunk%20And%20Hot%20Girls%20(Feat.%20Mos%20Def).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Drunk And Hot Girls (Feat. Mos Def)',
        duration: "05:13",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 25,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/09%20Flashing%20Lights%20(Feat.%20Dwele).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Flashing Lights',
        duration: "03:58",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 26,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/10%20Everything%20I%20Am%20(Feat.%20DJ%20Premier).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Everything I Am (Feat. DJ Premier)',
        duration: "03:48",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 27,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/11%20The%20Glory.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'The Glory',
        duration: "03:33",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 28,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/12%20Homecoming%20(Feat.%20Chris%20Martin).mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Homecoming',
        duration: "03:24",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
     {
        id: 29,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/13%20Big%20Brother.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Big Brother',
        duration: "04:47",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 30,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/14%20Good%20Night.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good night',
        duration: "03:06",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 48,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/Graduation/14%20Good%20Night.mp3",
        album: "Graduation",
        artist: 'Kanye West',
        title: 'Good night',
        duration: "03:06",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/Graduation.png',
    },
    {
        id: 49,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/KanyeWest/CollegeDropout/01%20Intro.mp3",
        album: "College Dropout",
        artist: 'Kanye West',
        title: 'Intro',
        duration: "03:06",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/CollegeDropout.png',
    },
        {
        "id": 119,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Coldest%20Winter.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Coldest Winter.mp3",
        "duration": "3:54",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 120,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Heartless.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Heartless.mp3",
        "duration": "3:40",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 121,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Bad%20News.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Bad News.mp3",
        "duration": "3:59",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 122,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Amazing.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Amazing.mp3",
        "duration": "3:59",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 123,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Paranoid.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Paranoid.mp3",
        "duration": "3:24",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 124,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20See%20You%20In%20My%20Nightmares.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " See You In My Nightmares.mp3",
        "duration": "4:18",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 125,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Pinocchio%20Story.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Pinocchio Story.mp3",
        "duration": "6:01",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 126,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Love%20Lockdown.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Love Lockdown.mp3",
        "duration": "4:35",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 127,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Street%20Lights.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Street Lights.mp3",
        "duration": "3:10",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 128,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Welcome%20To%20Heartbreak.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Welcome To Heartbreak.mp3",
        "duration": "4:30",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 129,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20Say%20You%20Will.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " Say You Will.mp3",
        "duration": "6:18",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    },
    {
        "id": 130,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/KanyeWest/808s/%20RoboCop.mp3",
        "album": "808s and heartbreak",
        "artist": "Kanye West",
        "title": " RoboCop.mp3",
        "duration": "4:34",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/KanyeWest/808s.png"
    }

]