import { AudioFile } from "../AudioFileType";


export const TaylorSwiftAudioFiles: AudioFile[] = [
    {
        id: 1,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/01%20willow.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'willow',
        duration: "03:34",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 2,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/02%20champagne%20problems.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'champagne problems',
        duration: "04:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 3,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/03%20gold%20rush.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'gold rush',
        duration: "03:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 4,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/04%20'tis%20the%20damn%20season.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "'tis the damn season",
        duration: "03:49",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 5,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/05%20tolerate%20it.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "tolerate it",
        duration: "04:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 6,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/06%20no%20body,%20no%20crime%20(feat.%20HAIM).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "no body, no crime (feat. HAIM)",
        duration: "03:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 7,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/07%20happiness.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "happiness",
        duration: "05:15",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 8,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/08%20dorothea.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "dorothea",
        duration: "03:45",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 9,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/10%20ivy.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "ivy",
        duration: "04:20",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 10,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/11%20cowboy%20like%20me.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "cowboy like me",
        duration: "04:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 11,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/12%20long%20story%20short.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "long story short",
        duration: "03:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 12,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/13%20marjorie.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "marjorie",
        duration: "04:17",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 13,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/14%20closure.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "closure",
        duration: "03:00",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 14,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/15%20evermore%20(feat.%20Bon%20Iver).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "evermore (feat. Bon Iver)",
        duration: "05:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 15,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/16%20right%20where%20you%20left%20me%20(bonus%20track).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "right where you left me (bonus track)",
        duration: "04:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 16,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/17%20it's%20time%20to%20go%20(bonus%20track).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: " it's time to go (bonus track)",
        duration: "04:14",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
        {
        "id": 38,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20cardigan.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " cardigan.",
        "duration": "4:34",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 17,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20invisible%20string.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " invisible string.",
        "duration": "4:14",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 18,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20my%20tears%20ricochet.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " my tears ricochet.",
        "duration": "4:17",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 19,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20exile%20%28feat.%20Bon%20Iver%29.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " exile (feat. Bon Iver).",
        "duration": "4:46",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 20,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20august.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " august.",
        "duration": "4:24",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 21,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20hoax.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " hoax.",
        "duration": "3:41",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 22,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20illicit%20affairs.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " illicit affairs.",
        "duration": "3:12",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 23,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20the%20lakes%20-%20bonus%20track.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " the lakes - bonus track.",
        "duration": "3:30",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 24,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20the%20last%20great%20american%20dynasty.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " the last great american dynasty.",
        "duration": "3:52",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 25,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20mad%20woman.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " mad woman.",
        "duration": "3:58",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 26,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20peace.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " peace.",
        "duration": "3:55",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 27,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20this%20is%20me%20trying.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " this is me trying.",
        "duration": "3:16",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 28,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20seven.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " seven.",
        "duration": "3:30",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 29,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20the%201.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " the 1.",
        "duration": "3:31",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 30,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20mirrorball.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " mirrorball.",
        "duration": "3:30",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 31,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20epiphany.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " epiphany.",
        "duration": "4:51",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    },
    {
        "id": 32,
        "uri": "https://bucket-memoryapp.nyc3.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/%20betty.",
        "album": "Folklore",
        "artist": "Taylor Swift",
        "title": " betty.",
        "duration": "4:55",
        "coverArt": "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png"
    }
];
