import { AudioFile } from "../AudioFileType";


export const TaylorSwiftAudioFiles: AudioFile[] = [
    {
        id: 1,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/01%20willow.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'willow',
        duration: "03:34",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 2,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/02%20champagne%20problems.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'champagne problems',
        duration: "04:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 3,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/03%20gold%20rush.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'gold rush',
        duration: "03:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 4,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/04%20'tis%20the%20damn%20season.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "'tis the damn season",
        duration: "03:49",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 5,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/05%20tolerate%20it.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "tolerate it",
        duration: "04:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 6,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/06%20no%20body,%20no%20crime%20(feat.%20HAIM).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "no body, no crime (feat. HAIM)",
        duration: "03:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 7,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/07%20happiness.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "happiness",
        duration: "05:15",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 8,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/08%20dorothea.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "dorothea",
        duration: "03:45",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 9,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/10%20ivy.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "ivy",
        duration: "04:20",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 10,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/11%20cowboy%20like%20me.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "cowboy like me",
        duration: "04:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 11,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/12%20long%20story%20short.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "long story short",
        duration: "03:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 12,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/13%20marjorie.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "marjorie",
        duration: "04:17",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 13,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/14%20closure.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "closure",
        duration: "03:00",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 14,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/15%20evermore%20(feat.%20Bon%20Iver).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "evermore (feat. Bon Iver)",
        duration: "05:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 15,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/16%20right%20where%20you%20left%20me%20(bonus%20track).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "right where you left me (bonus track)",
        duration: "04:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 16,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/17%20it's%20time%20to%20go%20(bonus%20track).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: " it's time to go (bonus track)",
        duration: "04:14",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 31,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/The%201.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "The 1",
        duration: "03:30",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
     {
        id: 32,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Cardigan.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "cardigan",
        duration: "03:59",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 33,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/The%20Last%20Great%20American%20Dynasty.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "The Last Great American Dynasty",
        duration: "03:51",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 34,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Exile.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "exile (feat. Bon Iver)",
        duration: "04:45",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
     {
        id: 35,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/My%20Tears%20Ricochet.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "my tears ricochet",
        duration: "04:15",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
     {
        id: 36,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Mirrorball.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "mirroball",
        duration: "03:28",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
     {
        id: 37,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Seven.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "seven",
        duration: "03:28",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
      {
        id: 38,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/August.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "august",
        duration: "04:21",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
     {
        id: 39,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/This%20Is%20Me%20Trying.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "this is me trying",
        duration: "03:15",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 40,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Illicit%20Affairs.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "illicit affairs",
        duration: "03:10",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 41,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Invisible%20String.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "invisible string ",
        duration: "04:12",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
     {
        id: 42,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Mad%20Woman.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "mad woman ",
        duration: "03:57",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 43,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Epiphany.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "epiphany ",
        duration: "04:49",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 44,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Betty.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "betty ",
        duration: "04:54",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 45,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Peace.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "peace ",
        duration: "03:54",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
    {
        id: 46,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/Hoax.mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "hoax ",
        duration: "03:40",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
     {
        id: 47,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Folklore/The%20Lakes%20(Bonus%20Track).mp3",
        album: "Folklore",
        artist: 'Taylor Swift',
        title: "The Lakes (Bonus Track) ",
        duration: "03:31",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Folklore.png',
    },
];
