export interface AudioFile {
    id: number;
    uri: string;
    artist: string;
    album: string;
    title: string;
    duration: string;
    coverArt: string;
}


export const audioFiles: AudioFile[] = [
    {
        id: 1,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/01%20willow.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'willow',
        duration: "03:34",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 2,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/02%20champagne%20problems.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'champagne problems',
        duration: "04:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 3,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/03%20gold%20rush.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: 'gold rush',
        duration: "03:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 4,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/04%20'tis%20the%20damn%20season.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "'tis the damn season",
        duration: "03:49",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 5,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/05%20tolerate%20it.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "tolerate it",
        duration: "04:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 6,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/06%20no%20body,%20no%20crime%20(feat.%20HAIM).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "no body, no crime (feat. HAIM)",
        duration: "03:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 7,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/07%20happiness.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "happiness",
        duration: "05:15",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 8,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/08%20dorothea.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "dorothea",
        duration: "03:45",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 9,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/10%20ivy.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "ivy",
        duration: "04:20",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 10,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/11%20cowboy%20like%20me.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "cowboy like me",
        duration: "04:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 11,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/12%20long%20story%20short.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "long story short",
        duration: "03:35",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 12,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/13%20marjorie.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "marjorie",
        duration: "04:17",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 13,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/14%20closure.mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "closure",
        duration: "03:00",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
    {
        id: 14,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/15%20evermore%20(feat.%20Bon%20Iver).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "evermore (feat. Bon Iver)",
        duration: "05:04",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 15,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/16%20right%20where%20you%20left%20me%20(bonus%20track).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: "right where you left me (bonus track)",
        duration: "04:05",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
     {
        id: 16,
        uri: "https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Songs/TaylorSwift/Evermore/17%20it's%20time%20to%20go%20(bonus%20track).mp3",
        album: "Evermore",
        artist: 'Taylor Swift',
        title: " it's time to go (bonus track)",
        duration: "04:14",
        coverArt: 'https://bucket-memoryapp.nyc3.cdn.digitaloceanspaces.com/Covers/TaylorSwift/Evermore.png',
    },
];
